version: '3'
services:
     elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
       container_name: elasticsearch
       networks:
           docker-elk:

     kibana:
       image: docker.elastic.co/kibana/kibana:5.4.3
       container_name: kibana
       environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9200"
       networks:
          - docker-elk
       depends_on:
          - elasticsearch
     zookeeper:
       image: wurstmeister/zookeeper:3.4.6
       expose:
          - "2181"
     kafka-1:
       image: wurstmeister/kafka
       depends_on: 
          - zookeeper
       restart: on-failure:3
       ports:
          - 9092
       environment:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     postg:
       image: postgres
       restart: always
       environment:
          - POSTGRES_USER:'postgres'
          - POSTGRES_PASSWORD:'postgres'
          - POSTGRES_DB:'postgres'
       ports:
          - 5432
     scanner:
       image: cgreen010/malware-check
       depends_on:
          - zookeeper
          - kafka-1
          - postg
          - elasticsearch
          - kibana
       ports:
          - 5000
networks:
  docker-elk:
    driver: bridge